---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: windows-pv
spec:
  capacity:
    storage: 64Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/windows-storage  # You can change this to a location based on your environment

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: windows-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
  volumeMode: Filesystem
  storageClassName: manual  # Ensure to change this if you have a different StorageClass set in your Railway/Kubernetes setup

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: windows
  labels:
    name: windows
spec:
  replicas: 1
  selector:
    matchLabels:
      app: windows
  template:
    metadata:
      labels:
        app: windows
    spec:
      containers:
        - name: windows
          image: dockurr/windows
          env:
            - name: VER
              value: "5.14"  # Version of your app (adjust as needed)
          volumeMounts:
            - mountPath: /storage  # Mount /storage to the Persistent Volume
              name: windows-storage
              readOnly: false
      volumes:
        - name: windows-storage
          persistentVolumeClaim:
            claimName: windows-pvc
