---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: windows-pv
spec:
  capacity:
    storage: 64Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/windows-storage  # Adjust this path as needed based on your environment
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: windows-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
  volumeMode: Filesystem
  storageClassName: manual  # Use the appropriate StorageClass if you have one configured
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: windows
  labels:
    name: windows
spec:
  replicas: 1
  selector:
    matchLabels:
      app: windows
  template:
    metadata:
      labels:
        app: windows
    spec:
      containers:
        - name: windows
          image: dockurr/windows
          env:
            - name: VER
              value: "5.14"  # Set the version environment variable or remove if not required
          volumeMounts:
            - mountPath: /storage  # This is where the container will access the storage
              name: windows-storage
              readOnly: false
      volumes:
        - name: windows-storage
          persistentVolumeClaim:
            claimName: windows-pvc
